language: c

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.0    RUN_COVER=false  RACO_TEST_OPTIONS=
    - RACKET_VERSION=6.0.1  RUN_COVER=false  RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.1    RUN_COVER=false  RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.1.1  RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.2    RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.2.1  RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.3    RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.4    RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.5    RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.6    RUN_COVER=true   RACO_TEST_OPTIONS=-e
    - RACKET_VERSION=6.7    RUN_COVER=true   RACO_TEST_OPTIONS=-e

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --installation --deps search-auto --link
      $TRAVIS_BUILD_DIR/point-free-doc
      $TRAVIS_BUILD_DIR/point-free-lib
      $TRAVIS_BUILD_DIR/point-free-test
  - if [ "$RUN_COVER" = true ]; then raco pkg install --installation --auto cover cover-coveralls; fi

script:
  - raco test $RACO_TEST_OPTIONS -p point-free-lib point-free-test
  - if [ "$RUN_COVER" = true ]; then raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p point-free-lib point-free-test; fi
